### ISSUE TITLE
Instagram App Completed! Yay!

### ISSUE THREAD

**Issue by hshssingh4** [hshssingh4/Instagram#1]
As this was the final app of our course except the final project of course, I thought of giving this one my everything. Loved making this app and will definitely be building upon this in near future. Thanks for giving me a chance to build such wonderful apps with you. Thanks a lot! Also, please don't forget to review my app. /cc @codepathreview

**Comment by minhkhang1795** [comment]
Hurray!! You have become more Swift competent right now!!

:+1: Congratulations on finishing the final assignment! It's impressive to realize how far you've come in the first half of the class, going from building a simple tip calculator to a full Instagram app with your own backend.

In your app, I see that you did a really, really great job to implement such wonderful functionalities. Some seem trivial at look, but not really easy to implement (i.e. the dismissing keyboard func,...) All the smallest functionalities worth a try and effort and I really appreciate your impressive work. Below is my specific feedback:
- Nice implementation of the Sign up page
- It looks like I can create a new user and be able to edit profile/cover picture of other existing users :-? However, the app crashes when it tries to show the updated image. (sorry if I did edit the profile/cover images in your Parse server :P)
- It also appears that the app sometimes crashes after I update my own cover image and go around to see my other posts.
- I love the scrolling effect when the title of a post still stays at the top, waiting for another title comes to take its place. :100: 
- From a Home scene, I click on a picture to show a user profile. Then, I move to the Post tab and try to upload the photo from my library. The app crashes, however, at let `vc = nc.topViewController as! HomeViewController`. I believe your `topViewController`, in this case, is no longer `HomeViewController`.
- Great work on the photo zoom! :smile: 

We hope you enjoyed the final assignment. Parse is a great service that makes building a backend app much easier. We have a detailed [Project 6 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_6_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

From here on out there are no more assignments as the focus shifts to the final group project. You'll be working over the next several weeks to build your app idea with your team and then finishing the class with a demo day! Good luck!

**Comment by hshssingh4** [comment]
Thanks for such a great feedback! Didn't get much time to look over the finished app before submitting due to time constraints but most of them have been fixed as I am continuously working on this app now to fix all those to the best of my ability. Cheers!
